*** Variables ***
${calendar}    //span[contains(text(), 'Calendar')]
${create_event}    //button[contains(text(), 'Create')]
${sidebar_widget_birthdays}    //div[contains(@class, 'sidebar-widget-birthdays')]
${user_birth_name}    //span[contains(@class, 'user-birth-name')]
${user_birth_date}    //span[contains(@class, 'user-birth-date')]
${cnn_selector}    //body//span
${vn_express_selector}    //body//a
